name: lib-selection
channels:
  - conda-forge
dependencies:
  - python==3.5
  - numpy
  - pip
  - pip:
    - pandas
    - numpy
    - scipy
    - matplotlib
    - tqdm
  - conda:
    - scikit-learn==0.19.1
    - rdkit
    - py3dmol
